[package]
name = "parse-ia"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
env_logger.workspace = true
html-escape.workspace = true
log.workspace = true
mailparse.workspace = true
md5 = "0.7"
pdf-extract = "0.7"
quoted_printable.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tempfile = "3"
